train-line-name=Express-Line-A
%prod.train-line-name=Production-Line-C

#quarkus.log.category."io.quarkus.oidc".level=DEBUG

## Container image tagging properties
quarkus.container-image.registry=${CONTAINER_IMAGE_REGISTRY}
quarkus.container-image.group=quarkus-training
quarkus.container-image.name=train-line-service
quarkus.container-image.tag=latest

## Container native image build properties
quarkus.container-image.build=true
quarkus.container-image.builder=jib
quarkus.container-image.push=true
quarkus.jib.platforms=linux/amd64

# k8s Service configuration
quarkus.kubernetes.expose=true
quarkus.kubernetes.service-type=load-balancer

# StationService Configuration
%prod.station-service/mp-rest/url=http://station-service:80
%dev.station-service/mp-rest/url=http://localhost:8081
%prod.station-service/mp-rest/token-client = station-service

# --- PostgreSQL Datasource Configuration ---
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=user
%prod.quarkus.datasource.password=quarkus
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://postgres-postgresql:5432/trainline_db

# Create the database schema automatically on startup
%prod.quarkus.hibernate-orm.database.generation=update

