train-line-name=Express-Line-A
%prod.train-line-name=Production-Line-C

## Container image tagging properties
quarkus.container-image.group=localhost/smessner
quarkus.container-image.name=train-line-service
quarkus.container-image.tag=latest

## Container native image build properties
quarkus.native.container-build=true
quarkus.native.container-runtime=podman
quarkus.container-image.build=true
quarkus.container-image.builder=podman